// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiDotNet.Utils;

#nullable disable

namespace WebApiDotNet.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20260830230627_UpdateModel")]
    partial class UpdateModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApiDotNet.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasAnnotation("Relational:JsonPropertyName", "description");

                    b.Property<string>("ImageBase64")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "imageBase64");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasAnnotation("Relational:JsonPropertyName", "title");

                    b.HasKey("Id");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("WebApiDotNet.Models.CourseVideo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("FKCourseId")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "fkCourseId");

                    b.Property<string>("VideoTitle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasAnnotation("Relational:JsonPropertyName", "videoTitle");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasAnnotation("Relational:JsonPropertyName", "videoUrl");

                    b.HasKey("Id");

                    b.HasIndex("FKCourseId");

                    b.ToTable("CourseVideos");

                    b.HasAnnotation("Relational:JsonPropertyName", "videoList");
                });

            modelBuilder.Entity("WebApiDotNet.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthToken")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasAnnotation("Relational:JsonPropertyName", "email");

                    b.Property<string>("FirstName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasAnnotation("Relational:JsonPropertyName", "firstName");

                    b.Property<bool>("IsAuthenticated")
                        .HasColumnType("bit")
                        .HasAnnotation("Relational:JsonPropertyName", "isAuthenticated");

                    b.Property<bool>("IsStudent")
                        .HasColumnType("bit")
                        .HasAnnotation("Relational:JsonPropertyName", "isStudent");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "password");

                    b.Property<string>("Phone")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasAnnotation("Relational:JsonPropertyName", "phone");

                    b.Property<string>("Surname")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasAnnotation("Relational:JsonPropertyName", "surname");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("WebApiDotNet.Models.UserCourse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("FKCourseId")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "fkCourseId");

                    b.Property<int>("FKUserId")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "fkUserId");

                    b.HasKey("Id");

                    b.HasIndex("FKUserId");

                    b.ToTable("UserCourses", (string)null);

                    b.HasAnnotation("Relational:JsonPropertyName", "courseList");
                });

            modelBuilder.Entity("WebApiDotNet.Models.UserVideo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("FKListId")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "fkListId");

                    b.Property<bool>("IsWatched")
                        .HasColumnType("bit")
                        .HasAnnotation("Relational:JsonPropertyName", "isWatched");

                    b.HasKey("Id");

                    b.HasIndex("FKListId");

                    b.ToTable("UserVideos", (string)null);

                    b.HasAnnotation("Relational:JsonPropertyName", "videoList");
                });

            modelBuilder.Entity("WebApiDotNet.Models.CourseVideo", b =>
                {
                    b.HasOne("WebApiDotNet.Models.Course", "Course")
                        .WithMany("Videos")
                        .HasForeignKey("FKCourseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Course");
                });

            modelBuilder.Entity("WebApiDotNet.Models.UserCourse", b =>
                {
                    b.HasOne("WebApiDotNet.Models.User", "User")
                        .WithMany("CourseList")
                        .HasForeignKey("FKUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebApiDotNet.Models.UserVideo", b =>
                {
                    b.HasOne("WebApiDotNet.Models.UserCourse", "UserCourse")
                        .WithMany("VideoList")
                        .HasForeignKey("FKListId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("UserCourse");
                });

            modelBuilder.Entity("WebApiDotNet.Models.Course", b =>
                {
                    b.Navigation("Videos");
                });

            modelBuilder.Entity("WebApiDotNet.Models.User", b =>
                {
                    b.Navigation("CourseList");
                });

            modelBuilder.Entity("WebApiDotNet.Models.UserCourse", b =>
                {
                    b.Navigation("VideoList");
                });
#pragma warning restore 612, 618
        }
    }
}
